### ISSUE TITLE
Libra submodule configured with ssh access

### ISSUE THREAD

**Issue by 39otrebla** [libra/libra-client-sdk-go#28]
As per the title, being both projects (this and Libra) public repositories I believe it would make more sense to use HTTP access to link LIbra as submodule.

**Comment by xli** [comment]
could you be more specific? I don't understand your request.

**Comment by 39otrebla** [comment]
[this](https://github.com/libra/libra-client-sdk-go/blob/master/.gitmodules) should point to the `https` URL of the repository, IMHO.

Otherwise, developers need to have an ssh-key configured in GitHub and loaded in their ssh-agent to be able to fetch the submodule.

**Comment by xli** [comment]
thanks, will updated

**Comment by xli** [comment]
resolved by https://github.com/libra/libra-client-sdk-go/pull/30
